# Generated by Django 4.1.3 on 2022-11-27 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('first_name_draft', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('last_name_draft', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('email_draft', models.EmailField(max_length=254)),
                ('languages', models.CharField(max_length=255)),
                ('languages_draft', models.CharField(max_length=255)),
                ('technologies', models.CharField(max_length=255)),
                ('technologies_draft', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('position_draft', models.CharField(max_length=50)),
                ('starting_date', models.DateField()),
                ('starting_date_draft', models.DateField()),
                ('ending_date', models.DateField()),
                ('ending_date_draft', models.DateField()),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=60)),
                ('project_name_draft', models.CharField(max_length=60)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.cv')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDescriptionPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('description_draft', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=255)),
                ('university_name_draft', models.CharField(max_length=255)),
                ('graduation_date', models.DateField()),
                ('graduation_date_draft', models.DateField()),
                ('faculty', models.CharField(max_length=255)),
                ('faculty_draft', models.CharField(max_length=255)),
                ('gpa', models.FloatField()),
                ('gpa_draft', models.FloatField()),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.cv')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceDescriptionPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('description_draft', models.CharField(max_length=255)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.experience')),
            ],
        ),
    ]
