# Generated by Django 4.1.3 on 2022-11-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_cv_phone_number_cv_phone_number_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='cv',
            name='image_draft',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
